server:
  port: 9000

spring:
  application:
    name: proxy

  cloud:
    gateway:
      routes:
        - id: producto
          uri: http://localhost:8081
          predicates:
            - Path=/productos/**

        - id: venta
          uri: http://localhost:8082
          predicates:
            - Path=/ventas/**

        - id: usuarios
          uri: http://localhost:8083
          predicates:
            - Path=/api/usuarios/**, /api/admin/**, /api/soporte/**, /api/v1/admin/usuarios/**

        - id: logistica
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/envios/**

